# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  global:
    TWINE_USERNAME: corp-0
    TWINE_PASSWORD:
      secure: 9jcsB3jHY41yPhv+OXDC2w==
    TWINE_NON_INTERACTIVE: true
    PYPI_USERNAME: corp-0
    PYPI_PASSWORD:
      secure: 9jcsB3jHY41yPhv+OXDC2w==

  matrix:
      - PYTHON: "C:\\Python38-x64"
        WINDOWS_SDK_VERSION: "v7.1"
        PLAT_NAME: "win-amd64"
        PY_TAG: "py37"

build: false 

install:
  - echo "Installing stage..."
  - python --version
  - set PATH=%PYTHON%\\scripts;%PATH%
  - pip install -r requirements_dev.txt
  - pip install -r requirements_test.txt

test_script:
  - echo "Test stage..."
  - "%PYTHON%/Scripts/tox"

deploy_script:
  - echo "Deploy stage..."
  - setup.py changelog
  - setup.py publish