# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  global:
    TWINE_USERNAME: corp-0
    TWINE_PASSWORD:
      secure: 9jcsB3jHY41yPhv+OXDC2w==
  matrix:
    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"

    - PYTHON: "C:\\Python37"
      TOXENV: "py37"

    - PYTHON: "C:\\Python37-x64"
      TOXENV: "py37"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install -U tox virtualenv"
  - "%PYTHON%/Scripts/pip install wheel"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox"

deploy_script:
  provider: pypi
  distributions: sdist bdist_wheel
  user: corp-0
  password:
    secure: Dr0NgajRfiRKdrPOnh+MAQwb+EzNQKLzZZ9oS7VtJzLyK40dC19bb8+iK9q9Xh11YDS/vDeRmWjlCmMUuKwqCJCg+c42y7yeD3elRZPR6n/r4ZCjUuw1JtScdgb3/ueZuyHtHQ5tvJ7uIwuEY+MzvwMcVJLRsRJ4rkugze+h9i6Rod4mRBfQngBj3Brg0okeG5vvPXMxvrqRZTGJhjd4ucOH4ho5vO8RHqeBPTHopY6JtS1bKrrmFlV6N0TCuFhqnB0FY1qvrB2kUKEGasKMyDeFEK/8/QgDo9Wvs0jOPxBSSLVvvP6NXOusAG8IWMG96XZO9T61VcDCfdYANX8WcbMQQ3MMafnVVFp1t9YBkgiLDUmV8kSquX0Nuv/lFKTdX7sfM4IIPaLXGto+r4pVb8/g4Rv+UMd5mGjSCrV6C4d5N/M9nVwWjTKaTjDQPoGEdInab3lR+rxu5jk6j7WMZ/uUSKZ0UiwS1Czx/XY24Algm+ZzOHe5Pb3wPrYZnXnC5pFc1T2/mSxdvlEKT8B7NPht5dh9cmsci+iF1Zf2fuHsXG/q6hz85+haapVr4F5GSX/Fk0uClLY/3hfEJBLjidSM3aZWmp7jrsTQktO3ACHQwoVctdWbry9VbApVBIfenOmH3s+bJjNOfOdrhnTQPs7yqiVWd3XOk/lA+6/qmfM=
  on:
    tags: true
    repo: corp-0/jtac
    python: 3.7

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse