# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  global:
    TWINE_USERNAME: corp-0
    TWINE_PASSWORD:
      secure: 9jcsB3jHY41yPhv+OXDC2w==
    TWINE_NON_INTERACTIVE: true

  PYTHON: "C:\\Python37-x64"
  TOXENV: "py37"

install:
- pip install tox

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
- tox

deploy_script:
  - python setup.py sdist bdist_wheel
  - twine upload dist\*

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse