# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  global:
    TWINE_USERNAME: corp-0
    TWINE_PASSWORD:
      secure: 9jcsB3jHY41yPhv+OXDC2w==
    TWINE_NON_INTERACTIVE: true
    PYPI_USERNAME: corp-0
    PYPI_PASSWORD:
      secure: 9jcsB3jHY41yPhv+OXDC2w==
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      PY_TAG: "py37"

build: false 

install:
  - echo "Installing stage..."
  - "%PYTHON%\\python.exe -m pip install wheel nose"
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "pip3 install -r requirements_dev.txt"

test_script:
  - echo "Test stage..."
  - "python tox"

deploy_script:
  - echo "Deploy stage..."
  - "python -m setup.py changelog"
  - "python -m setup.py publish"