# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  global:
    TWINE_USERNAME: corp-0
    TWINE_PASSWORD:
      secure: 9jcsB3jHY41yPhv+OXDC2w==
    TWINE_NON_INTERACTIVE: true
  matrix:
  - TOXENV: "C:\\Python35-x64"
  - TOXENV: "C:\\Python36-x64"
  - TOXENV: "C:\\Python37-x64"

build: false 

install:
- pip install tox

test_script:
- tox

deploy_script:
  - python setup.py sdist bdist_wheel
  - twine upload dist\*