# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  global:
    TWINE_USERNAME: corp-0
    TWINE_PASSWORD:
      secure: 9jcsB3jHY41yPhv+OXDC2w==
  matrix:
    - PYTHON: "C:\\Python37-x64"
      TOXENV: "py37"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install -U tox virtualenv"
  - "%PYTHON%/Scripts/pip install wheel"
  - "%PYTHON%/Scripts/pip install -U twine"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox"

deploy_script:
  - "echo [pypi] > %USERPROFILE%\\.pypirc"
  - "echo username: %TWINE_USERNAME% >> %USERPROFILE%\\.pypirc"
  - "echo password: %TWINE_PASSWORD% >> %USERPROFILE%\\.pypirc"
  - python setup.py sdist bdist_wheel
  - twine upload dist\*

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse