# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  global:
    TWINE_USERNAME: corp-0
    TWINE_PASSWORD:
      secure: 9jcsB3jHY41yPhv+OXDC2w==
  matrix:
    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"

    - PYTHON: "C:\\Python37"
      TOXENV: "py37"

    - PYTHON: "C:\\Python37-x64"
      TOXENV: "py37"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install -U tox virtualenv"
  - "%PYTHON%/Scripts/pip install wheel"

artifacts:
  - path: dist\*

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox"

on_success:
  provider: pypi
  distributions: sdist bdist_wheel
  user: corp-0
  password: %TWINE_PASSWORD%
    on:
    tags: true
    repo: corp-0/jtac
    python: 3.7


#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse